#![cfg(test)]

use super::*;
use civic_identity::{
    Contract as IdentityContract, ContractClient as IdentityContractClient, STATUS_ACTIVE,
};
use civic_proposal::Contract as ProposalContract;
use civic_proposal::ContractClient as ProposalContractClient;
use soroban_sdk::{
    symbol_short,
    testutils::{Address as _, Ledger as _},
    Address, BytesN, ConversionError, Env, InvokeError, String,
};

/// `try_*` on a non-Result entrypoint returns
/// `Result<Result<T, ConversionError>, Result<soroban_sdk::Error, InvokeError>>`.
/// Contract errors surface as the `Ok(host_error)` arm; decode them back to
/// the crate's `Error` enum via the `TryFrom` impl generated by `contracterror`.
fn assert_contract_err<T>(
    res: Result<Result<T, ConversionError>, Result<soroban_sdk::Error, InvokeError>>,
    expected: Error,
) {
    match res {
        Err(Ok(host_err)) => assert_eq!(Error::try_from(host_err).ok(), Some(expected)),
        Err(Err(_)) => panic!("expected contract error, got host invoke error"),
        Ok(_) => panic!("expected contract error {expected:?}, got success"),
    }
}

const HOUR: u64 = 3_600;
const T0: u64 = 1_000_000;

fn b(env: &Env, v: u8) -> BytesN<32> {
    BytesN::from_array(env, &[v; 32])
}

struct Fixture {
    env: Env,
    admin: Address,
    voter1: Address,
    voter2: Address,
    identity: Address,
    proposal: Address,
    vote: Address,
    proposal_id: u64,
}

/// Registers identity + proposal + vote contracts wired together, issues two
/// eligible credentials, creates one proposal windowed [T0+2h, T0+10h].
fn fixture() -> Fixture {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_timestamp(T0);

    let admin = Address::generate(&env);
    let proposer = Address::generate(&env);
    let voter1 = Address::generate(&env);
    let voter2 = Address::generate(&env);

    let identity_id = env.register(IdentityContract, (admin.clone(),));
    let identity = IdentityContractClient::new(&env, &identity_id);
    identity.issue(&voter1, &b(&env, 0x01), &symbol_short!("citizen"));
    identity.issue(&voter2, &b(&env, 0x02), &symbol_short!("citizen"));

    let proposal_id_addr = env.register(ProposalContract, (admin.clone(),));
    let proposal = ProposalContractClient::new(&env, &proposal_id_addr);
    let proposal_id = proposal.create(
        &proposer,
        &b(&env, 0x11),
        &b(&env, 0x12),
        &b(&env, 0x13),
        &String::from_str(
            &env,
            "bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi",
        ),
        &b(&env, 0x14),
        &(T0 + 2 * HOUR),
        &(T0 + 10 * HOUR),
    );

    let vote_id = env.register(
        Contract,
        (admin.clone(), identity_id.clone(), proposal_id_addr.clone()),
    );

    Fixture {
        env,
        admin,
        voter1,
        voter2,
        identity: identity_id,
        proposal: proposal_id_addr,
        vote: vote_id,
        proposal_id,
    }
}

fn vote_client(f: &Fixture) -> ContractClient<'_> {
    ContractClient::new(&f.env, &f.vote)
}

fn open_window(f: &Fixture) {
    f.env.ledger().set_timestamp(T0 + 3 * HOUR);
}

#[test]
fn public_vote_tallies_once_per_voter() {
    let f = fixture();
    open_window(&f);
    let c = vote_client(&f);

    let t = c.cast_public(&f.proposal_id, &f.voter1, &0);
    assert_eq!(t.total, 1);
    assert_eq!(t.public_votes, 1);
    assert_eq!(t.commitment_votes, 0);
    assert_eq!(t.verification_mode, Symbol::new(&f.env, "public_v1"));
    assert_eq!(t.counts.get(0).unwrap(), 1);

    let t = c.cast_public(&f.proposal_id, &f.voter2, &1);
    assert_eq!(t.total, 2);
    assert_eq!(t.counts.get(0).unwrap(), 1);
    assert_eq!(t.counts.get(1).unwrap(), 1);

    assert!(c.has_voted_public(&f.proposal_id, &f.voter1));
    assert!(!c.has_voted_public(&f.proposal_id, &f.admin));

    // stored tally readable
    let stored = c.get_tally(&f.proposal_id).unwrap();
    assert_eq!(stored.total, 2);
    assert_eq!(stored.verification_mode, Symbol::new(&f.env, "public_v1"));
}

#[test]
fn double_public_vote_rejected() {
    let f = fixture();
    open_window(&f);
    let c = vote_client(&f);
    c.cast_public(&f.proposal_id, &f.voter1, &0);
    let res = c.try_cast_public(&f.proposal_id, &f.voter1, &2);
    assert_contract_err(res, Error::AlreadyVoted);
}

#[test]
fn voting_before_open_rejected() {
    let f = fixture();
    // t = T0, proposal opens at T0 + 2h
    let c = vote_client(&f);
    let res = c.try_cast_public(&f.proposal_id, &f.voter1, &0);
    assert_contract_err(res, Error::ProposalNotOpen);
}

#[test]
fn voting_after_close_rejected() {
    let f = fixture();
    f.env.ledger().set_timestamp(T0 + 11 * HOUR);
    let c = vote_client(&f);
    let res = c.try_cast_public(&f.proposal_id, &f.voter1, &0);
    assert_contract_err(res, Error::ProposalNotOpen);
}

#[test]
fn unknown_proposal_rejected() {
    let f = fixture();
    open_window(&f);
    let c = vote_client(&f);
    let res = c.try_cast_public(&77, &f.voter1, &0);
    assert_contract_err(res, Error::ProposalNotFound);
}

#[test]
fn ineligible_voter_rejected() {
    let f = fixture();
    open_window(&f);
    let c = vote_client(&f);

    // no credential at all
    let stranger = Address::generate(&f.env);
    let res = c.try_cast_public(&f.proposal_id, &stranger, &0);
    assert_contract_err(res, Error::NotEligible);

    // credential revoked mid-window
    let identity = IdentityContractClient::new(&f.env, &f.identity);
    identity.revoke(&f.voter2, &b(&f.env, 0xee));
    let res = c.try_cast_public(&f.proposal_id, &f.voter2, &0);
    assert_contract_err(res, Error::NotEligible);
    assert_eq!(identity.get_credential(&f.voter2).unwrap().status, 2u32);
    assert_eq!(STATUS_ACTIVE, 0u32);
}

#[test]
fn commitment_requires_membership_root() {
    let f = fixture();
    open_window(&f);
    let c = vote_client(&f);

    let res = c.try_cast_commitment(
        &f.proposal_id,
        &0,
        &b(&f.env, 0xa1),
        &b(&f.env, 0xc1),
        &b(&f.env, 0x99),
        &b(&f.env, 0xd1),
    );
    assert_contract_err(res, Error::RootNotSet);
}

#[test]
fn commitment_wrong_root_rejected() {
    let f = fixture();
    open_window(&f);
    let c = vote_client(&f);
    c.set_membership_root(&f.proposal_id, &b(&f.env, 0x77));

    let res = c.try_cast_commitment(
        &f.proposal_id,
        &0,
        &b(&f.env, 0xa1),
        &b(&f.env, 0xc1),
        &b(&f.env, 0x99), // wrong root
        &b(&f.env, 0xd1),
    );
    assert_contract_err(res, Error::RootMismatch);
}

#[test]
fn commitment_ballot_counts_with_honest_mode() {
    let f = fixture();
    open_window(&f);
    let c = vote_client(&f);
    c.set_membership_root(&f.proposal_id, &b(&f.env, 0x77));

    let t = c.cast_commitment(
        &f.proposal_id,
        &1,
        &b(&f.env, 0xa1),
        &b(&f.env, 0xc1),
        &b(&f.env, 0x77),
        &b(&f.env, 0xd1),
    );
    assert_eq!(t.total, 1);
    assert_eq!(t.commitment_votes, 1);
    assert_eq!(t.public_votes, 0);
    // honesty: commitment mode is recorded, never zk_*
    assert_eq!(t.verification_mode, Symbol::new(&f.env, "commitment_v1"));
    assert_eq!(t.counts.get(1).unwrap(), 1);
    assert!(c.nullifier_seen(&f.proposal_id, &b(&f.env, 0xa1)));
    assert!(!c.nullifier_seen(&f.proposal_id, &b(&f.env, 0xa2)));
    assert_eq!(c.membership_root(&f.proposal_id), Some(b(&f.env, 0x77)));
}

#[test]
fn duplicate_nullifier_rejected() {
    let f = fixture();
    open_window(&f);
    let c = vote_client(&f);
    c.set_membership_root(&f.proposal_id, &b(&f.env, 0x77));

    c.cast_commitment(
        &f.proposal_id,
        &0,
        &b(&f.env, 0xa1),
        &b(&f.env, 0xc1),
        &b(&f.env, 0x77),
        &b(&f.env, 0xd1),
    );
    let res = c.try_cast_commitment(
        &f.proposal_id,
        &2,
        &b(&f.env, 0xa1), // same nullifier
        &b(&f.env, 0xc2),
        &b(&f.env, 0x77),
        &b(&f.env, 0xd1),
    );
    assert_contract_err(res, Error::NullifierUsed);
}

#[test]
fn mixed_modes_tally_together() {
    let f = fixture();
    open_window(&f);
    let c = vote_client(&f);
    c.set_membership_root(&f.proposal_id, &b(&f.env, 0x77));

    c.cast_public(&f.proposal_id, &f.voter1, &0);
    c.cast_commitment(
        &f.proposal_id,
        &0,
        &b(&f.env, 0xa1),
        &b(&f.env, 0xc1),
        &b(&f.env, 0x77),
        &b(&f.env, 0xd1),
    );

    let t = c.get_tally(&f.proposal_id).unwrap();
    assert_eq!(t.total, 2);
    assert_eq!(t.public_votes, 1);
    assert_eq!(t.commitment_votes, 1);
    assert_eq!(t.counts.get(0).unwrap(), 2);
    // mode escalates only to commitment_v1 — never beyond what is proven
    assert_eq!(t.verification_mode, Symbol::new(&f.env, "commitment_v1"));
}

#[test]
fn membership_root_is_admin_only() {
    let f = fixture();
    open_window(&f);
    let c = vote_client(&f);
    f.env.set_auths(&[]);
    let res = c.try_set_membership_root(&f.proposal_id, &b(&f.env, 0x77));
    assert!(res.is_err(), "non-admin must be rejected by auth");
}

#[test]
fn wiring_getters_expose_cross_contract_addresses() {
    let f = fixture();
    let c = vote_client(&f);
    assert_eq!(c.admin(), f.admin);
    assert_eq!(c.identity_contract(), f.identity);
    assert_eq!(c.proposal_contract(), f.proposal);
}
