/**
 * Report assembly and hashing.
 *
 * The two digests produced here are the values anchored in
 * `BrujulaAccountability.anchor(proposal_id, report_hash, evidence_hash, ...)`:
 *
 *   evidenceHash = H(canonical JSON of the evidence set)  — the sources;
 *   reportHash   = H(canonical JSON of the report body)  — the findings.
 *
 * Both are reproducible by any third party that re-retrieves the sources and
 * confirms their `contentHash`. Nothing in the report is generated by a model,
 * so there is nothing non-deterministic to disagree about.
 */

import { sha256Utf8 } from "@brugulacivica/sdk";

import { canonicalize, type Json } from "./canonical.js";
import { evaluateClaim, rollUpStatus } from "./rules.js";
import type { ClaimRule, EvidenceSet, HermesReport, RetrievedSource } from "./types.js";

/**
 * The hashed projection of a source.
 *
 * `text` is included deliberately: hashing only metadata would let a source's
 * content change without changing the evidence hash, which would defeat the
 * point. A verifier re-fetches the source, checks `contentHash`, then recomputes
 * `evidenceHash`.
 *
 * Fields deliberately EXCLUDED: `retrievedAt`, `httpStatus`, `finalUrl` and
 * `error`. All four vary between two fetches of the *same* bytes — the HTTP
 * `Date` header changes every second, a redirect may or may not happen, a proxy
 * may answer 200 or 203. Including them made `evidence_hash` differ on every
 * run, which would make the on-chain anchor impossible for a third party to
 * reproduce. The digest identifies the evidence *content*; the retrieval
 * timestamp is provenance and lives in the evidence file, not in the digest.
 */
function sourceProjection(source: RetrievedSource): Json {
  return {
    byteLength: source.byteLength,
    contentHash: source.contentHash,
    contentType: source.contentType,
    status: source.status,
    text: source.text,
    url: source.url,
  };
}

export async function evidenceHash(evidence: EvidenceSet): Promise<string> {
  const payload: Json = {
    sources: evidence.sources.map(sourceProjection),
    subject: evidence.subject,
  };
  return sha256Utf8(canonicalize(payload));
}

export interface BuildReportOptions {
  /** Injected for determinism in tests; defaults to now. */
  generatedAt?: Date;
}

/**
 * Evaluate every rule against the evidence set and produce the report.
 *
 * The report body that is hashed excludes `generatedAt`, so re-running Hermes
 * over unchanged sources reproduces `reportHash` even at a different wall-clock
 * time. `generatedAt` is still returned for display, and it is already part of
 * the evidence set via each source's `retrievedAt`.
 */
export async function buildReport(
  evidence: EvidenceSet,
  rules: readonly ClaimRule[],
  opts: BuildReportOptions = {},
): Promise<HermesReport> {
  const seenRules = new Set<string>();
  for (const rule of rules) {
    if (seenRules.has(rule.id)) {
      throw new Error(`regla duplicada: ${rule.id} (los ids deben ser únicos y estables)`);
    }
    seenRules.add(rule.id);
  }

  const findings = rules.map((rule) => evaluateClaim(evidence, rule));
  const body: Json = {
    findings: findings.map((f) => ({
      claim: f.claim,
      detail: f.detail,
      matchedSourceIndices: f.matchedSourceIndices,
      retrievedSourceCount: f.retrievedSourceCount,
      ruleDescription: f.ruleDescription,
      ruleId: f.ruleId,
      status: f.status,
    })),
    overallStatus: rollUpStatus(findings),
    subject: evidence.subject,
  };

  return {
    subject: evidence.subject,
    findings,
    overallStatus: rollUpStatus(findings),
    evidenceHash: await evidenceHash(evidence),
    reportHash: await sha256Utf8(canonicalize(body)),
    generatedAt: (opts.generatedAt ?? new Date()).toISOString(),
    failedSourceCount: evidence.sources.filter((s) => s.status !== "RETRIEVED").length,
  };
}